name = "hono-slack"
main = "src/index.ts"
compatibility_date = "2022-10-10"

# https://developers.cloudflare.com/workers/wrangler/configuration/#node-compatibility
node_compat = true

[vars]
FAKE_VAR = "fake-var"
# The necessary secrets are:
# - SLACK_BOT_TOKEN
# - SLACK_SIGNING_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these